services:
  artillery:
    image: artilleryio/artillery:2.0.23
    container_name: artillery
    working_dir: /app
    # NOTE: report는 확인용으로 사용 (2.0.22부터 report는 Artillery Cloud에서만 가능)
    command: ["run", "playwright-artillery.yml", "--output", "/app/output/artillery-report.json"]
    volumes:
      - .:/app
    environment:
      - PHASE1_DURATION=1
      - PHASE1_ARRIVAL_RATE=1
      - TEST_ID=local
      - OLTP_METRICS_ENDPOINTS=http://localhost:4318
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 2048M